import { Job, Machine } from "./types";

export const machines: Machine[] = [
  { id: "M-01", name: "CNC Mill 01", status: "Running" },
  { id: "M-02", name: "CNC Mill 02", status: "Running" },
  { id: "M-03", name: "Lathe 01", status: "Idle" },
  { id: "M-04", name: "Lathe 02", status: "Maintenance" },
  { id: "M-05", name: "Press 01", status: "Running" },
  { id: "M-06", name: "Welding Station A", status: "Running" },
  { id: "M-07", name: "Injection Molder 01", status: "Idle" },
  { id: "M-08", name: "Laser Cutter 01", status: "Offline" },
];

export const mockJobs: Job[] = [
  {
    id: "JOB-1042",
    productName: "Aluminum Bracket A-200",
    customer: "Northwind Aerospace",
    quantity: 500,
    dueDate: "2026-09-21",
    status: "In Progress",
    machine: "CNC Mill 01",
    notes:
      "Material delivered. Tool wear on insert #3 — monitor and replace at 400 units.",
  },
  {
    id: "JOB-1043",
    productName: "Steel Shaft Assembly",
    customer: "Pioneer Motors",
    quantity: 1200,
    dueDate: "2026-09-25",
    status: "Pending",
    machine: "Lathe 01",
    notes:
      "Awaiting raw stock delivery from supplier. Expected arrival 2026-09-20.",
  },
  {
    id: "JOB-1044",
    productName: "Titanium Flange Plate",
    customer: "Vertex Energy",
    quantity: 75,
    dueDate: "2026-09-19",
    status: "Delayed",
    machine: "CNC Mill 02",
    notes:
      "Machine downtime on 2026-09-17 due to coolant system failure. Recovery plan in place, est. 2-day slip.",
  },
  {
    id: "JOB-1045",
    productName: "Plastic Housing Enclosure",
    customer: "Apex Electronics",
    quantity: 3000,
    dueDate: "2026-09-30",
    status: "In Progress",
    machine: "Injection Molder 01",
    notes:
      "First article inspection passed. Running 500 units/hr. On schedule.",
  },
  {
    id: "JOB-1046",
    productName: "Copper Heat Sink V2",
    customer: "ThermaCore Systems",
    quantity: 850,
    dueDate: "2026-09-22",
    status: "Completed",
    machine: "CNC Mill 01",
    notes: "Completed 2026-09-18. All units passed QC. Ready for pickup.",
  },
  {
    id: "JOB-1047",
    productName: "Stainless Valve Body",
    customer: "FlowTech Industrial",
    quantity: 320,
    dueDate: "2026-09-20",
    status: "Delayed",
    machine: "Lathe 02",
    notes:
      "Lathe 02 under scheduled maintenance until 2026-09-21. Job queued to resume upon completion.",
  },
  {
    id: "JOB-1048",
    productName: "Composite Panel Sheet",
    customer: "AeroStruct Composites",
    quantity: 200,
    dueDate: "2026-10-05",
    status: "Pending",
    machine: "Press 01",
    notes: "Tooling setup scheduled for 2026-09-23. Material in stock.",
  },
  {
    id: "JOB-1049",
    productName: "Brass Connector Fitting",
    customer: "Meridian Plumbing Supply",
    quantity: 5000,
    dueDate: "2026-09-28",
    status: "In Progress",
    machine: "CNC Mill 02",
    notes:
      "High-volume run. Batch 1 of 3 complete. Running at 95% efficiency.",
  },
  {
    id: "JOB-1050",
    productName: "Aluminum Gear Housing",
    customer: "Northwind Aerospace",
    quantity: 150,
    dueDate: "2026-09-23",
    status: "In Progress",
    machine: "CNC Mill 01",
    notes: "Secondary operation (anodizing) subcontracted to finish 2026-09-22.",
  },
  {
    id: "JOB-1051",
    productName: "Welded Steel Frame",
    customer: "Pioneer Motors",
    quantity: 60,
    dueDate: "2026-09-19",
    status: "Delayed",
    machine: "Welding Station A",
    notes:
      "Welder called in sick 2026-09-18. Backup operator assigned, est. 1-day delay.",
  },
  {
    id: "JOB-1052",
    productName: "Precision Brass Bushing",
    customer: "FlowTech Industrial",
    quantity: 2000,
    dueDate: "2026-10-10",
    status: "Pending",
    machine: "Lathe 01",
    notes: "New part — requires first article inspection before full run.",
  },
  {
    id: "JOB-1053",
    productName: "Laser-Cut Steel Plate",
    customer: "Vertex Energy",
    quantity: 400,
    dueDate: "2026-09-26",
    status: "Completed",
    machine: "Laser Cutter 01",
    notes: "Completed 2026-09-16. Shipped to customer 2026-09-17.",
  },
  {
    id: "JOB-1054",
    productName: "Anodized Aluminum Enclosure",
    customer: "Apex Electronics",
    quantity: 1000,
    dueDate: "2026-10-02",
    status: "In Progress",
    machine: "CNC Mill 02",
    notes: "Machining complete. In anodizing queue — cosmetic finish batch 2.",
  },
  {
    id: "JOB-1055",
    productName: "Forged Steel Hub",
    customer: "Meridian Plumbing Supply",
    quantity: 250,
    dueDate: "2026-09-21",
    status: "Pending",
    machine: "Press 01",
    notes: "Die inspection scheduled 2026-09-20. Material on hand.",
  },
  {
    id: "JOB-1056",
    productName: "Custom Titanium Mount",
    customer: "AeroStruct Composites",
    quantity: 30,
    dueDate: "2026-09-24",
    status: "Completed",
    machine: "CNC Mill 01",
    notes: "Low-volume specialty part. Completed and delivered 2026-09-15.",
  },
];
